#!/usr/bin/env python

import typer
import json
import yaml
import os


base_path = os.getcwd()

app = typer.Typer()


def json_to_yaml(inp: str) -> str:
    return yaml.dump(json.loads(inp))


def yaml_to_json(inp: str) -> str:
    return json.dumps(yaml.load(inp, Loader=yaml.SafeLoader), indent=4)


@app.command(
    name="jyc",
    help="jyc <file_path>",
    epilog="Thanks for using jyc! :)"
)
def jyc(file_path: str) -> None:
    if not file_path.endswith(("json", "yaml", "yml")):
        return
    with open(file_path, 'r') as f:
        inp = f.read()
        if file_path.endswith("json"):
            print(json_to_yaml(inp))
        else:
            print(yaml_to_json(inp))


if __name__ == "__main__":
    app()
